### ISSUE TITLE
line 79 invalid syntax

### ISSUE THREAD

**Issue by GuiLoL** [n-agi/ORD8-Savecode-Generator#2]
on line 79 I get a invalid syntax error on the " after print. any fix for this?

**Comment by n-agi** [comment]
I wrote this code a year ago; Use `python2` since `print` is now used as a function in python3.

**Comment by GuiLoL** [comment]
yeah thanks. I noticed it was for a older version of ord.

**Comment by n-agi** [comment]
It is a 2 years old repo so yeah.. I'll try to reverse-engineer ORD9 after all of my personal works are done :)
